import exceptionsLib.*

program exceptions {
	const a = new A()
	
	var i = 0
	try {
		a.m0() 
		console.println("No exception raised")
	}
	catch e : MyException
		e.printStackTrace()
	then always 
		i = i + 1 
	
	if (i > 0) {
		console.println("i is positive")
	}
	else {
		console.println("i is zero !")
	}
	console.println("End of program")

}